# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
---
ansible_host: "192.168.210.6"
hostname: "core-02"
post_login_message: |
                #####################################################################################
                #                     You are successfully logged in to: core-02                    #
                #####################################################################################
lo_ip: "172.16.176.12/32"
router_id: "172.16.176.12"
vlan_interfaces:
  - { id: 'vlan200', ip: '172.16.177.3/24', vrr: '172.16.177.1/24', vlan: '200', vrf: 'OOB' }
  - { id: 'vlan300', ip: '172.16.178.3/24', vrr: '172.16.178.1/24', vlan: '300', vrf: 'INBAND' }
  - { id: 'vlan400', ip: '172.16.179.3/24', vrr: '172.16.179.1/24', vlan: '400', vrf: 'INBAND' }
  - { id: 'vlan500', ip: '172.16.180.3/24', vrr: '172.16.180.1/24', vlan: '500', vrf: 'INBAND' }
  - { id: 'vlan900', ip: '192.168.110.3/24', vrr: '192.168.110.1/24', vlan: '900', vrf: 'GPU' }
nve_vxlan: { her: 'evpn', source: '172.16.176.12' }
bgp_routerid: '172.16.176.12'
prefix_list:
  - { id: 'ALL_PREFIXES', rule: [{ id: '10', match: '0.0.0.0/0', max_len: '32' }] }
  - { id: 'EXIT_LOCAL_IF', rule: [{ id: '10', match: '172.16.176.6/32', max_len: '32' }] }
  - { id: 'INBAND_LOCAL_IF', rule: [{ id: '10', match: '172.16.176.4/32', max_len: '32' },{ id: '20', match: '172.16.178.3/32', max_len: '32' },{ id: '30', match: '172.16.179.3/32', max_len: '32' },{ id: '40', match: '172.16.180.3/32', max_len: '32' }] }
  - { id: 'INBAND_PREFIXES', rule: [{ id: '10', match: '172.16.178.0/24', max_len: '32' },{ id: '20', match: '172.16.179.0/24', max_len: '32' },{ id: '30', match: '172.16.180.0/24', max_len: '32' },{ id: '40', match: '172.16.176.4/32', max_len: '32' }] }
  - { id: 'ERA_PREFIXES', rule: [{ id: '10', match: '172.16.176.0/21', max_len: '24' },{ id: '20', match: '172.16.176.0/24', max_len: '32' }] }
  - { id: 'LOCAL_OOB_LOOPBACK', rule: [{ id: '10', match: '172.16.176.2/32', max_len: '32' }] }
  - { id: 'OOB_LOCAL_IF', rule: [{ id: '10', match: '172.16.176.2/32', max_len: '32' },{ id: '20', match: '172.16.177.3/32', max_len: '32' }] }
  - { id: 'OOB_PREFIXES', rule: [{ id: '10', match: '172.16.177.0/24', max_len: '32' },{ id: '20', match: '172.16.176.2/32', max_len: '32' }] }
  - { id: 'VTEP_PREFIXES', rule: [{ id: '5', match: '172.16.176.8/29', max_len: '32' }] }
vrf_config:
  - { id: 'EXIT', lo: '172.16.176.6/32', vlan: 3004, vni: '5004', rd: '172.16.176.12:5004' }
  - { id: 'INBAND', lo: '172.16.176.4/32', vlan: 3002, vni: '5002', rd: '172.16.176.12:5002' }
  - { id: 'GPU', lo: '192.168.110.6/32', vlan: 3003, vni: '5003', rd: '172.16.176.12:5003' }
  - { id: 'OOB', lo: '172.16.176.2/32', vlan: 3001, vni: '5001', rd: '172.16.176.12:5001' }
