{
 "title": "Network Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Reachable vs. Unreachable switches",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (\n  max by (net.host.name) (up)\n)",
     "legendFormat": "Reachable Switches"
    },
    {
     "expr": "sum by () (\n  1 - max by (net.host.name) (up)\n) or 0",
     "legendFormat": "Unreachable Switches"
    }
   ]
  },
  {
   "title": "Stats from Live Switches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (net.host.name) (nvswitch_interface_tc_tx_octet))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count by(service.instance.id) (nvrouting_bgp_peer_state))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count by(net.host.name) (nvswitch_interface_oper_state{interface=\"swp1s0\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stats from Live Switches - Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (net.host.name) (nvswitch_interface_tc_tx_octet))",
     "legendFormat": "Interface Stats"
    },
    {
     "expr": "count(count by(service.instance.id) (nvrouting_bgp_peer_state))",
     "legendFormat": "Routing Stats"
    },
    {
     "expr": "count(count by(net.host.name) (nvswitch_interface_oper_state{interface=\"swp1s0\"}))",
     "legendFormat": "Link Stats"
    }
   ]
  },
  {
   "title": "CPU Utilization by Switch (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (net.host.name) (\n    rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\n  ) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization by Switch (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\n(\n  1 -\n  avg by (net.host.name) (\n    node_memory_MemAvailable_bytes\n    /\n    node_memory_MemTotal_bytes\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregate Bandwidth (Gbit/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (net.host.name) (\n  rate(nvswitch_interface_ether_stats_octets[$__rate_interval])\n) * 8 / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregate Interface Errors (errors/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (net.host.name) (\n  rate(nvswitch_interface_ether_stats_drop_events[$__rate_interval])\n)",
     "legendFormat": "{{net.host.name}} errors/s"
    }
   ]
  },
  {
   "title": "Interfaces up per switch",
   "type": "barchart",
   "description": "This panel shows number of active links on the switches",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count by(net.host.name) (nvswitch_interface_oper_state == 1)",
     "legendFormat": "{{net.host.name}}"
    }
   ]
  },
  {
   "title": "Link Down Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(nvswitch_interface_carrier_down_changes_total[$__rate_interval])",
     "legendFormat": "{{net.host.name}} {{interface}}"
    }
   ]
  },
  { "title": "Routing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "BGP (IPv4 + IPv6) Routes Received per Switch",
   "type": "timeseries",
   "description": "Number of IPv4 + IPv6 unicast routes received from the BGP neighbor after applying any policies. This count is the number of routes present in the post-policy Adj-RIB-In for the neighbor.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (service.instance.id) (\n  nvrouting_bgp_peer_rib_adj_in_ipv4_unicast{state=\"Established\"}\n  + nvrouting_bgp_peer_rib_adj_in_ipv6_unicast{state=\"Established\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVPN Prefixes Received",
   "type": "timeseries",
   "description": "Number of EVPN routes received from the BGP neighbor after applying any policies. This count is the number of routes present in the post-policy Adj-RIB-In for the neighbor.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (service.instance.id) (\n  nvrouting_bgp_peer_rib_adj_in_l2vpn_evpn{state=\"Established\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Peer States per Switch",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (service.instance.id, state) (\n  nvrouting_bgp_peer_state\n)",
     "legendFormat": "{{service.instance.id}} : {{state}}"
    }
   ]
  },
  {
   "title": "Number of BGP routes per VRF",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "expr": "nvrouting_rib_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "BGP Peer Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "targets": [
    { "expr": "nvrouting_bgp_peer_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Switch Software Versions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "targets": [
    { "expr": "node_os_info", "legendFormat": "__auto" }
   ]
  }
 ]
}