{
 "title": "Kubernetes Global Metrics",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "type",
    "label": "workload_type",
    "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\".+\"}, workload_type)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overall Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Running",
     "type": "stat",
     "description": "Number of Pods Running",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespaces",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_namespace_created{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(count by (node) (kube_node_info{cluster=\"$cluster\"}))"
      }
     ]
    },
    {
     "title": "Kubernetes Node Status",
     "type": "stat",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kube_node_status_condition{condition=\"Ready\", status=\"true\"}) by (node) OR \n(1 - max(kube_node_status_condition{condition=\"Ready\", status!=\"true\"}) by (node))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kubernetes Resource Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(kube_namespace_labels)", "legendFormat": "Namespaces" },
      {
       "expr": "sum(kube_pod_container_status_running)",
       "legendFormat": "Running Containers"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
       "legendFormat": "Running Pods"
      },
      { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
      { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
      { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
      { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" },
      { "expr": "sum(kube_statefulset_labels)", "legendFormat": "Statefulsets" },
      { "expr": "sum(kube_daemonset_labels)", "legendFormat": "Daemonsets" },
      {
       "expr": "sum(kube_persistentvolumeclaim_info)",
       "legendFormat": "Persistent Volume Claims"
      },
      { "expr": "sum(kube_hpa_labels)", "legendFormat": "Horizontal Pod Autoscalers" },
      { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmaps" },
      { "expr": "sum(kube_secret_info)", "legendFormat": "Secrets" },
      { "expr": "sum(kube_networkpolicy_labels)", "legendFormat": "Network Policies" },
      {
       "expr": "count(count by (node) (kube_node_info))",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "CPU Usage by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", cluster=\"$cluster\"}) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload Breakdown (Filter Above)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by Workload",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload_type=~\"$type\"}\n) by (workload, workload_type)\n",
       "legendFormat": "{{workload}} - {{workload_type}}"
      }
     ]
    },
    {
     "title": "CPU Usage by Pod",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Usage by Workload",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload_type=~\"$type\"}\n) by (workload, workload_type)\n",
       "legendFormat": "{{workload}} - {{workload_type}}"
      }
     ]
    },
    {
     "title": "Memory Usage by Pod",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod)"
      }
     ]
    }
   ]
  }
 ]
}