{
 "title": "CPU + Storage Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (node_hwmon_temp_celsius {instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Idle Time ",
   "type": "timeseries",
   "description": "This query calculates the average idle CPU time (mode=\"idle\") per instance over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$instance\"}[$__rate_interval])) by (instance)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU System Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(rate(node_cpu_seconds_total{mode=\"system\", instance=~\"$instance\"}[$__rate_interval])) by (instance)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU User Time",
   "type": "timeseries",
   "description": "Filtered by instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\", instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemFree_bytes{instance=~\"$instance\"}  - node_memory_Buffers_bytes{instance=~\"$instance\"}  - node_memory_Cached_bytes{instance=~\"$instance\"} ",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  { "title": "Storage metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Disk Read Time Latency",
   "type": "heatmap",
   "description": "Measured in seconds/read",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(device) (rate(node_disk_read_time_seconds_total{instance=~\"$instance\"}[5m])) \r\n/ sum by(device) (rate(node_disk_reads_completed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg by (device) (rate(node_disk_io_time_seconds_total{instance =~ \"$instance\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write Time Latency",
   "type": "heatmap",
   "description": "Measured in seconds/write",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(device) (rate(node_disk_write_time_seconds_total{instance=~\"$instance\"}[5m])) \r\n/ sum by(device) (rate(node_disk_writes_completed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\", instance=~\"$instance\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$instance\"})",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}