---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# GSL Plane 2 group variables - 2-8-9-800 Deployment
# ============================================================================
asn: 4260397298

vlan900_vrr: 192.168.16.1/20

gpu_subnet: 192.168.16.0/20
