---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# OOB Switch Group Variables - 2-4-3-200 Deployment
# ============================================================================
pre_login_message: |
                #####################################################################################
                #  Welcome to NVIDIA Cumulus VX (TM)                                                #
                #  NVIDIA Cumulus VX (TM) is a community supported virtual appliance designed       #
                #  for experiencing, testing and prototyping NVIDIA Cumulus' latest technology. #
                #  For any questions or technical support, visit our community site at:             #
                #  https://www.nvidia.com/en-us/support                                             #
                #####################################################################################

timezone: 'Etc/Zulu'

# Common OOB switch configuration
oob_vlan: '200'
spine_bond_members:
  - 'swp49'
  - 'swp51'

