#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Fix DNS resolution after dnsmasq setup
# Run this ON the dhcp-oob server

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║              Fixing DNS Resolution                           ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo

# Check current DNS configuration
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Current DNS configuration:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cat /etc/resolv.conf
echo

# Backup existing resolv.conf
echo "Backing up /etc/resolv.conf..."
sudo cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)

# Check if dnsmasq is running
if systemctl is-active --quiet dnsmasq; then
    echo "✓ dnsmasq is running"
    
    # Option 1: Use dnsmasq on localhost
    echo
    echo "Setting DNS to use local dnsmasq (127.0.0.1)..."
    echo "# Generated by fix-dns.sh - Use local dnsmasq" | sudo tee /etc/resolv.conf
    echo "nameserver 127.0.0.1" | sudo tee -a /etc/resolv.conf
    
else
    echo "⚠ dnsmasq is not running - using Google DNS directly"
    
    # Option 2: Use Google DNS directly
    echo
    echo "Setting DNS to Google DNS (8.8.8.8, 8.8.4.4)..."
    echo "# Generated by fix-dns.sh - Google DNS" | sudo tee /etc/resolv.conf
    echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
    echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf
fi

# Make it immutable (optional - prevents changes)
# sudo chattr +i /etc/resolv.conf

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "New DNS configuration:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cat /etc/resolv.conf
echo

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Testing DNS resolution:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if ping -c 1 www.google.com &> /dev/null; then
    echo "✅ DNS resolution working!"
else
    echo "❌ DNS still not working"
    echo
    echo "Try these troubleshooting steps:"
    echo "  1. Check dnsmasq: sudo systemctl status dnsmasq"
    echo "  2. Check logs: sudo journalctl -u dnsmasq -n 30"
    echo "  3. Test manually: nslookup www.google.com 8.8.8.8"
fi

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Done!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

