---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# GSL-PLANE2-01 Host-Specific Variables - 2-8-9-800 Deployment
# ============================================================================
ansible_host: 192.168.200.221
mac_address: 48:b0:2d:5d:22:c1
ip_assignment_mode: dhcp

hostname: gsl-plane2-01
plane: 2
lo_ip: 10.2.1.1/32

vlan900_ip: 192.168.16.2/20

vrf_gpu_loopback: 10.2.1.11/32

plane_mate_lo_ip: 10.2.1.2
