---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# OOB-SWITCH-01 - 2-8-9-800 Deployment
# ============================================================================
ansible_host: 192.168.200.2
hostname: oob-switch-01
svi_ip: 192.168.200.2/24
default_gateway: 192.168.200.1
access_ports: swp1-6,25-42,45-47,53-57,60-61
uplink_ports: swp1-6,25-42,45-47,49-57,60-61
spine_bond_members:
- swp49
- swp50
- swp51
- swp52
mac_address: 48:b0:2d:af:35:ec
ip_assignment_mode: dhcp

