---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# N/S Core - core-01
# ============================================================================
hostname: core-01
lo_ip: 172.16.1.1/32
router_id: 172.16.1.1
asn: 4200100001

# VRF loopbacks
vrf_loopbacks:
  OOB: 172.16.1.17/32
