---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# N/S Leaf 2 - csl-02
# ============================================================================
hostname: csl-02
lo_ip: 172.16.1.5/32
router_id: 172.16.1.5
asn: 4200100005

# VLAN SVI IPs (per-host)
vlan200_ip: 172.16.2.3/24
vlan300_ip: 172.16.3.3/24
vlan400_ip: 172.16.4.3/24

# VRF loopbacks
vrf_loopbacks:
  OOB: 172.16.1.21/32
  INBAND: 172.16.1.23/32
  STORAGE: 172.16.1.25/32
