---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# E/W Plane 1 Leaf 1 - gl-plane1-01
# ============================================================================
hostname: gl-plane1-01
lo_ip: 10.1.1.1/32
router_id: 10.1.1.1
asn: 4200101101

# GPU SVI IP (plane 1)
vlan900_ip: 192.168.0.2/20

# GPU VRF loopback
vrf_gpu_loopback: 10.1.1.11/32
