---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# E/W Plane 2 Leaf 3 - gl-plane2-03
# ============================================================================
hostname: gl-plane2-03
lo_ip: 10.1.2.3/32
router_id: 10.1.2.3
asn: 4200102103

# GPU SVI IP (plane 2)
vlan900_ip: 192.168.16.4/20

# GPU VRF loopback
vrf_gpu_loopback: 10.1.2.13/32
