---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# E/W Plane 2 Leaf 4 - gl-plane2-04
# ============================================================================
hostname: gl-plane2-04
lo_ip: 10.1.2.4/32
router_id: 10.1.2.4
asn: 4200102104

# GPU SVI IP (plane 2)
vlan900_ip: 192.168.16.5/20

# GPU VRF loopback
vrf_gpu_loopback: 10.1.2.14/32
