---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# E/W Plane 2 Spine 1 - gs-plane2-01
# ============================================================================
hostname: gs-plane2-01-ipp6
lo_ip: 10.1.2.5/32
router_id: 10.1.2.5
asn: 4200102100
