---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# E/W Plane 1 Spine 1 - gs-plane1-01
# ============================================================================
hostname: gs-plane1-01-ipp6
lo_ip: 10.1.1.5/32
router_id: 10.1.1.5
asn: 4200101100
