---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# OOB SN2201 - oob-switch-07
# ============================================================================
hostname: oob-switch-07
lo_ip: 172.16.1.39/32
router_id: 172.16.1.39
asn: 4200100016

# VLAN 200 SVI IP
vlan200_ip: 172.16.2.10/24

# VRF OOB loopback
vrf_oob_loopback: 172.16.1.39/32
