---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# ============================================================================
# OOB SN2201 - oob-switch-03
# ============================================================================
hostname: oob-switch-03
lo_ip: 172.16.1.35/32
router_id: 172.16.1.35
asn: 4200100012

# VLAN 200 SVI IP
vlan200_ip: 172.16.2.6/24

# VRF OOB loopback
vrf_oob_loopback: 172.16.1.35/32
