---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

ansible_host: 192.168.200.4
hostname: oob-switch-03
svi_ip: 192.168.200.4/24
default_gateway: 192.168.200.1
access_ports: swp1-5,10-15,27-40,53-57,60-61
uplink_ports: swp1-5,10-15,27-40,49-57,60-61
spine_bond_members:
- swp49
- swp50
- swp51
- swp52
mac_address: 48:b0:2d:ce:00:e8
ip_assignment_mode: dhcp
