# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
- name: restart dhcp
  service:
    name: isc-dhcp-server
    state: restarted